### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by shunkakinoki** [deliverybot/deliverybot#46]
Full implementation in GitHub actions.

A SaaS implementation in https://deliverybot.dev/ is awesome, 
but an alternative official implementation through GitHub actions will be really great for those who can't offer self-hosted implementations subsequent to September 2020

**Comment by jerr0328** [comment]
From my understanding, you can't easily trigger another workflow from GitHub Actions, so you might need to still have something that can respond to webhooks in order to trigger the deployment action. Some actions do mention some workarounds: https://github.com/marketplace/actions/deployment-action#notes

**Comment by colinjfw** [comment]
Ya exactly, Deliverybot is implemented as a fully separate GitHub App because the amount of coordination and matching of events is outside of the scope of what could be done only inside a GitHub action.
